### ISSUE TITLE
User, billing address, and shipping address data objects

### ISSUE THREAD

**Issue by dmcclory** [tweag/cybersourcery_demo_site#1]
Noticing that we ended up creating a more programmer friendly mapping of "normal terms" to SOP field names. e.g.:

``` ruby
def user_params
  {
    email:     params[:bill_to_email],
    username:  params[:bill_to_email],
    firstname: params[:ship_to_forename],
    lastname:  params[:ship_to_surname],
    password:  params[:merchant_secure_data1]
  }.delete_if {|key, value| value.blank? }
end
```

we might want to take it a step further and turn them into data objects which know about the field names that cybersource is expecting.

**Comment by nicholaides** [comment]
:+1: Sounds like a good idea to me

**Comment by toppa** [comment]
@nicholaides @dmcclory I'd like some feedback on how I have things setup at this point. I don't have data objects like Dan was suggesting. Here's what I have: [the Payment model](https://github.com/promptworks/cybersourcery/blob/master/app/models/payment.rb) and [the form that uses it](https://github.com/promptworks/cybersourcery/blob/master/app/views/payments/new.html.slim). I'm wondering what next steps to take on this aspect of the project.

My thoughts:
- I'm hesitant to do a full-on form builder, as that could get us involved with a lot of view-level implementation detail that I'm thinking is best left to the user.
- I have mappings of labels to field names, but - looking at the sample code Dan provided - I'm hesitant to go further (and that might even be too much). Mapping things like "username" to "bill_to_email" seems like a very app specific decision - not something to do in the gem. We could provide an abstraction layer to support arbitrary mappings, but I'm wondering if dealing with that would be more work for the user than just coding the form UI directly themselves.

These are just initial thoughts, so feedback is welcome. If there are things in Sunguard (or elsewhere) that can help drive requirements here, let me know!

**Comment by nicholaides** [comment]
> I'm hesitant to do a full-on form builder, as that could get us involved with a lot of view-level implementation detail that I'm thinking is best left to the user.

Agreed

> Mapping things like "username" to "bill_to_email" seems like a very app specific decision - not something to do in the gem

Agreed

>  I'm wondering if dealing with that would be more work for the user than just coding the form UI directly themselves.

Agreed

After some more thought, I don't know if this feature would be that useful, at least at this point in the gem's development.

**Comment by toppa** [comment]
Ok - I'm closing this
