### ISSUE TITLE
Cybersource transaction types to support?

### ISSUE THREAD

**Issue by toppa** [tweag/cybersourcery_demo_site#12]
The existing Sunguard code is hardcoded to the "create_payment_token" transaction type. The Penn code is hardcoded to the "sale" type. 

Need to decide whether and how to make this configurable.

**Comment by nicholaides** [comment]
I think we should make it configurable. The Sundard app will also use
`update_payment_token`.

On Tue, Jul 29, 2014 at 9:34 AM, Michael Toppa notifications@github.com
wrote:

> The existing Sunguard code is hardcoded to the "create_payment_token"
> transaction type. The Penn code is hardcoded to the "sale" type.
> 
> Need to decide whether and how to make this configurable.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/promptworks/cybersourcery/issues/12.

## 

Mike Nicholaides
Software Engineer and Co-Founder at PromptWorks
www.promptworks.com
(267) 622-4729

**Comment by dmcclory** [comment]
I agree. I think that one starts a subscription (create_payment_token) and the other does a one-off payment (sale)

**Comment by toppa** [comment]
Thanks guys. I'll add a story for this
