### ISSUE TITLE
Sorcery should validate the signature/input

### ISSUE THREAD

**Issue by nicholaides** [tweag/cybersourcery_demo_site#19]
Because Cybersource has really bad error messages, it would be nice if Sorcery could do some validation of the input.

For example, I'd like it to validate the signature (if possible).

Also, Cybersource returns a 500 error if you provide it with an array of query params. Sorcery could give you a helpful error message if you try to do this.

**Comment by toppa** [comment]
:+1:

**Comment by toppa** [comment]
@nicholaides Greg mentioned [the Rack::TranslatingProxy project](https://github.com/promptworks/rack-translating_proxy) to me and was wondering if it should supercede the existing Sorcery code. Please let me know what you think.

**Comment by toppa** [comment]
I'm checking for the cryptic errors I've run into with Cybersource (passing arrays, and a signed_field_names value that exceeds 700 characters). I'm not checking the signature. That would be great to do, so I've [added it as an issue](https://github.com/promptworks/cybersourcery_testing/issues/2)
