### ISSUE TITLE
form helper should setup all of the hidden fields

### ISSUE THREAD

**Issue by dmcclory** [tweag/cybersourcery_demo_site#2]
the Silent order post needs a number of hidden fields set up. we do that by:
1. creating a hash of
2. adding a piece of boilerplate to the templates:

```
- @signed_form_data.each do |key, value|
  input type="hidden" name=key value=value 
```

that should be moved into a helper.  we could either create our own method which wraps simple_form_for and always sets up the fields, or we could create a helper which could be inserted into a form, like so:

```
simple_form_for ... do |f|
  setup_hidden_fields
end
```

of the two, I lean towards the second.

**Comment by nicholaides** [comment]
I agree. I like the second better, too.

**Comment by toppa** [comment]
I wrote something similar to this for Penn. In their case it's in PHP, and uses their custom framework, so we'd have to re-write it. To get an idea of how it works, this is how it's called (example from the readme). We could simplify it to work more like what Dan is suggesting

``` php
$this->require_panel_lib(get_project_home('utilities') . '/lib/SecurePaymentFormDataBuilder.phl');
$form_builder = new SecurePaymentFormDataBuilder();
$form_builder->set_fluid_sql_error_notification_email('your_notification@email.com');
$form_builder->set_user_id(1234);
$form_builder->set_client_app_slug('your-app-slug');
$form_builder->set_amount(100);
$form_params = $form_builder->run();

foreach ($form_params as $k=>$v) {
  $tpl->assign($k, $v);
}
```

**Comment by toppa** [comment]
I should clarify that is for their "shopping cart" page, not the credit card form itself. In Penn's credit card form, the view has:

``` erb
<% @signed_form_data.each do |key, value| %>
  <%= hidden_field_tag key, value %>
<% end %>
```

So we could abstract that some more too

**Comment by toppa** [comment]
I've got this and lots of goodies in [the helper for the payment form](https://github.com/promptworks/cybersourcery/blob/master/app/helpers/payments_helper.rb). You can see usage in [the payment form](https://github.com/promptworks/cybersourcery/blob/master/app/views/payments/pay.html.slim)

**Comment by toppa** [comment]
Note I also have JS that dynamically gives you a select list of US states if you pick the US as the country (it also switches back to being a simple text input if you don't pick the US). For this reason, I have the country select list near the top of the address section, instead of where it usually appears, at the bottom (for this feature to be helpful, country needs to come before state). This breaks convention for field order in address forms, but for what I think is a useful benefit. Feedback is welcome!
