### ISSUE TITLE
one gem or two?

### ISSUE THREAD

**Issue by dmcclory** [tweag/cybersourcery_demo_site#3]
I think we should keep it two one gem for now. Most people who are going to be using it will want to use it in the context of Rails. The primary advantage is that there'd be one place for all issues. I like the intention behind the idea - it would be nice if people could use this outside of Rails. 

What if we set up the project so that:

```
require 'cybersourcery'
```

would define the `CyberSource` space, with whatever is unrelated to rails. Then in the initializers we could have something like:

```
# in config/cybersorcery.rb
CyberSourcery.enable_rails!
```

which would evaluate rails specific code.

**Comment by nicholaides** [comment]
I like the idea of 1 gem, too. There would likely be a railtie in the gem that would either get loaded automatically, or loaded when you do

```
require 'cybersourcery/rails'
```

**Comment by toppa** [comment]
I've ended up with several Rails dependencies in my code, so I agree. We'll go with one gem, at least for now.
