### ISSUE TITLE
Submit basic credit card form securely

### ISSUE THREAD

**Issue by toppa** [tweag/cybersourcery_demo_site#6]
As a customer, I want my credit card transaction handled securely, so that I'm confident my personal and financial information is safe
- Set up the form to use https
- When the credit card form is submitted, dynamically sign form inputs, per Cybersource guidelines

**Comment by toppa** [comment]
Done. I ended up not using https. I had assumed Cybersource had required it, but they don't. It's a pain to setup on heroku, and I don't think it's really relevant to the goal of making the gem.

**Comment by nicholaides** [comment]
Agreed. Also, I don't think HTTPS is strictly necessary. Credit card data will go right to Cybersource's server via HTTPS. As long as the developer doesn't render sensitive data on the form, it will be fine.
